### ISSUE TITLE
keyword-popularity

### ISSUE THREAD

**Issue by tomek-he-him** [tomekwi/ideas#2]
# keyword-popularity

**Get the number of npm packages with a certain keyword.**

<p                                                                   >&nbsp;</p>

## Installation

```
$ npm install --global keyword-popularity
```

<p                                                                   >&nbsp;</p>

## Usage

  SYNOPSIS

```
Usage: keyword-popularity [options] ...<keyword>
```

  OPTIONS

```
-h  --help   Print a short synopsis (-h) or this usage info (--help)
```

  EXAMPLES

<pre>
$ keyword-popularity cli tool cli-tool
<b>KEYWORD    POPULARITY</b>
cli        2422
tool       497
cli-tool   0
</pre>

<p                                                                   >&nbsp;</p>

## Credits

Based on [npm-keyword](https://www.npmjs.com/package/npm-keyword) by @sindresorhus.

**Comment by tomekwi** [comment]
Speaking of you @sindresorhus – perhaps you know of such a tool already?

**Comment by tomek-he-him** [comment]
Published at http://npm.im/keyword-popularity
